#!/usr/bin/env bash
set -euo pipefail

show_help() {
  echo "Usage: $0 <reference> [<owner>/istio] [<owner>/proxy] [<owner>/envoy]"
  echo "  Prints the envoy commit SHA and Version for the specified tag of a referenced Istio."
  echo "  If no reference is specified, the default is master."
  echo "Examples:"
  echo "  $0 1.20.0"
  echo "  $0 2a7f00169241757f1fcea803df26d7e61148717d"
}

if [[ "$#" -eq 1 ]] && { [[ "$1" == "help" ]] || [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; }; then
  show_help
  exit 0
fi

ISTIO_REF="${1-master}"
ISTIO_REPO="${2-istio/istio}"
PROXY_REPO="${3-istio/proxy}"
ENVOY_REPO="${4-envoyproxy/envoy}"

raw_content_type="Accept: application/vnd.github.v3.raw"
proxy_latest_stable_sha=$(gh api -H "${raw_content_type}" repos/${ISTIO_REPO}/contents/istio.deps?ref=${ISTIO_REF} --jq '.[] | select(.repoName == "proxy") | .lastStableSHA')
envoy_sha=$(gh api -H "${raw_content_type}" repos/"${PROXY_REPO}"/contents/WORKSPACE?ref="${proxy_latest_stable_sha}" | grep 'ENVOY_SHA' | cut -d'"' -f2 | head -n 1)
envoy_version=$(gh api -H "${raw_content_type}" repos/"${ENVOY_REPO}"/contents/VERSION.txt?ref="${envoy_sha}")
base_image_distroless_with_iptables=$(gh api -H "${raw_content_type}" repos/"${ISTIO_REPO}"/contents/pilot/docker/Dockerfile.proxyv2?ref="${ISTIO_REF}" | grep 'iptables@') || echo 'no more special @iptables image'

echo "proxy SHA: ${proxy_latest_stable_sha}"
echo "envoy SHA: ${envoy_sha}"
echo "envoy version: ${envoy_version}"
echo "base image distroless with iptables: ${base_image_distroless_with_iptables}"
